# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

include $(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tablet/MIPI_DSI/dsi_addons/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tablet/MIPI_DSI/dsi_ctrl/Makefile

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/MIPI_DSI/dsi_common.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/MIPI_DSI/dsi_debug.o
