# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/lcd_tablet.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/lcd_drv.o

include $(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tablet/DisplayPort/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/lcd/lcd_tablet/MIPI_DSI/Makefile
