# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/MIPI_DSI/dsi_ctrl/dsi_ctrl_v1.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/MIPI_DSI/dsi_ctrl/dsi_ctrl_v2.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/MIPI_DSI/dsi_ctrl/dsi_ctrl_if.o
